### PR TITLE
Ruby 270 support

### PR DESCRIPTION
**Pull request by tijcolem**
This is a required gem in OpenStudio-server which is moving to ruby 2.7.x series. 

https://github.com/NREL/OpenStudio-server/blob/develop/server/Gemfile#L66

Proposed to bump gem version to 1.2.0 to support ruby change.

### CODE REVIEW

**Comment by tijcolem** [comment]
looks like CI is failing due to wrong version. I'll fix. This CI should be moved to GitHub actions.  @nllong want me to move it?

**Comment by nllong** [comment]
> looks like CI is failing due to wrong version. I'll fix. This CI should be moved to GitHub actions. @nllong want me to move it?

Yes, it would be great to move this!  Thanks @tijcolem

**Comment by tijcolem** [comment]
@nllong I added in placeholder for github actions.  Looking at the old [.travis ](https://github.com/NREL/OpenStudio-analysis-gem/blob/develop/.travis.yml) there are no running tests. We can add those when and if they become available. 

I pulled a 1.1.X-LTS branch in support of ruby 2.5.x series.  Once this is merged in, this moves to ruby 2.7 as it has deps that use 2.7.

**Comment by nllong** [comment]
Thanks @tijcolem! I'm unsure why travis was blank. I think I ran these tests locally because we test against an OpenStudio server instance. Let me take a swag at hooking something up.

**Comment by nllong** [comment]
@tijcolem --okay, i've added the basic tests... not the OpenStudio Server yet.

**Review by nllong — APPROVED** [review]

**Comment by tijcolem** [comment]
@nllong awesome! looks great. I just removed my test placeholder and updated the image tag to use :develop of openstudio.

**Pull request merged**
